name: html5-build
run-name: Performing web build
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
jobs:
  perform-export:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Godot headless
        run: |
          curl -L https://github.com/godotengine/godot/releases/download/3.5.3-stable/Godot_v3.5.3-stable_linux_headless.64.zip -o Godot_v3.5.3-stable_linux_headless.64.zip
          unzip Godot_v3.5.3-stable_linux_headless.64.zip

      - name: Download Godot export templates
        run: |
          curl -L https://github.com/godotengine/godot/releases/download/3.5.3-stable/Godot_v3.5.3-stable_export_templates.tpz -o Godot_v3.5.3-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/templates/3.5.3.stable/
          unzip -j Godot_v3.5.3-stable_export_templates.tpz "templates/*" -d ~/.local/share/godot/templates/3.5.3.stable/

      - name: Perform HTML5 export
        run: |
          mkdir -p build/HTML5
          ./Godot_v3.5.3-stable_linux_headless.64 --export HTML5 build/HTML5/pong.html
          mv build/HTML5/pong.html build/HTML5/index.html

      - name: Save build so we can use it to upload deployment in the next job
        uses: actions/upload-artifact@v3
        with:
          name: html5-build-artifact
          path: build/HTML5/

  update-deployment:
    needs: perform-export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deployment repository
        uses: actions/checkout@v4
        with:
          repository: austinclem1/austinclem1.github.io
          token: ${{ secrets.PAGES_PAT }}

      - name: Remove existing deployment files
        run: rm -rf demos/godot-web
      
      - name: Download new build
        uses: actions/download-artifact@v3
        with:
          name: html5-build-artifact
          path: demos/godot-web

      - name: Commit and push updated build
        run: |
          git config user.name "Build Bot"
          git config user.email "<>"
          git add demos/godot-web
          git commit -m "update godot-web deployment"
          git push origin main
